### ISSUE TITLE
Crash on world load (doesn't even start loading world)

### ISSUE THREAD

**Issue by ShootToKillSTK** [Patrigan/SlimierSlimes#1]
Forge version 36.0.35

I fixed the issue by taking the server config and putting it into default configs to load it each time, and edited it to allow spawning of normal slimes

- My guess is clashing with possibly quark and some other mods, I know quark adds a like slime caves that has slime blocks in it
- Or/also other mods add slime creatures 

I just noticed too that the crystal slimes attack can hit everything, really cool attack but it makes it attack any mobs just by going near it, which then makes the mob kill it, then it split and jumps and kills its own split slimes.. lol, should probably change that so at least it can't damage itself, and maybe other mobs then player too bc they don't fight back

And here's crash log and debug for the crash (the crash was a freeze, made Mc freeze and never fully crashed, I just hit x to close because stuck)

https://gist.github.com/ShootToKillSTK/1d5fc7ec7981e7e4fff57ea7cda774eb

Lovely mod though!

**Comment by Patrigan** [comment]
This is very interesting information. Long modlist though, so a fix will take me a short while to sort out.

I do expect some mods simply won't work without vanilla slimes being available, which is why the config is there. A modlist like this will likely still require that setting to be on. I might think of some other potential fixes for these incompats as well.

I will look into a good solution and your logs go a long way.

As for the crystal slime. I fixed that and the hotfix is getting uploaded to Curse.

**Comment by Patrigan** [comment]
Bug discovered. Fairly serious. Apparently all villagertrades got removed. Fixed on my end with a suggested adjustion for Dungeons Gear. Found a small other bug, though...

**Comment by Patrigan** [comment]
Fixed in 1.0.2
