### ISSUE TITLE
No difference in weight value. (1.16.5 - forge 36.0.45)

### ISSUE THREAD

**Issue by FurryApocalypse** [Patrigan/SlimierSlimes#4]
I just wanted to sugest to upgrade a little config of weight. 
While there was sightly difference when i drop weight from 300 to 50, there is no significant difference when i drop weight again to 1 from 50.
I wanted  to made them more rare couse in The End they spawn in midair and look like rain falling down to the void (probably couse we use betterend forge)
Its not an issue but some improvements would be realy cool.

**Comment by Patrigan** [comment]
In the next version, 1.1.0, currently in finalized testing, this issue has been resolved.

There's two parts to the fix: Slime weights can now be controlled very in depth and you can even remove slimes from a specific spawn location completely. I also made a fix that will prevent the overspawning in the end. The problem there was the incorrect bounding of weights (even in the end, endermen have only a 5 spawn weight and with 150-300 on slimes that means A LOT of slimes.) Sadly, this does mean that even setting it to 1 will still allow 1 in 6 end spawns to be a slime.

Should I consider adding a config option to increase the enderman spawn weight in the end? This would be a possibility, would this help? Don't want to do this by default, because it might impact other mods who meddle with the end.

**Comment by FurryApocalypse** [comment]
In my opinion if there is a way to go around and decrease weight only for slimes its good enough. Most of mods have config for their own mobs not for the vanilla one so i think the best way will be to not touch enderman's weight and wait for potentional feedback.

**Comment by Patrigan** [comment]
I figured as well. For now, that is what I have released and it is now available on Curseforge. Download 1.1.0 and let me know if your issues have been fixed :D
